twig:
    globals:
        app_gravatar: '@App\Utils\Gravatar'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_3_layout.html.twig']
